version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 2012:8080

# APP
  elyadata_scraper:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: elyadata_scraper
    volumes:
      - ./image:/app/image
    ports:
      - 1053:1053
    restart: always
    depends_on:
      - postgres
volumes:
  postgres-data: